name: notify publish

on:
  push:
    branches:
      - "main"

jobs:
  notify:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: Ilshidur/action-discord@master
        name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed."
